# Should be automatically generated (but its not right now!)
require "arrayize-spec"
require "blending/deepExtend-spec"
require "blending/Blender-spec"
require "blending/lodash-merge-spec"
require "blending/deepCloneDefaults-spec"
require "objects/getValueAtPath-spec"
require "objects/setValueAtPath-spec"
require "go-spec"
require "okv-spec"
require "mutate-spec"
require "spec-data"
require "type-spec"
require "isPlain-spec"
require "uberscore-spec"
