# Should be automatically generated (but its not right now!)
require "arrayize-spec"
require "deepCloneDefaults-spec"
require "deepExtend-spec"
require "go-spec"
require "okv-spec"
require "mutate-spec"
require "spec-data"
require "type-spec"
require "uberscore-spec"
